"""Added new tables

Revision ID: 3c470fb136d3
Revises: 
Create Date: 2024-06-23 22:21:54.010291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c470fb136d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('effector_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('action_timestamp', sa.DateTime(), nullable=True),
    sa.Column('detection_timestmap', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_effector_actions_action'), 'effector_actions', ['action'], unique=False)
    op.create_index(op.f('ix_effector_actions_action_timestamp'), 'effector_actions', ['action_timestamp'], unique=False)
    op.create_index(op.f('ix_effector_actions_detection_timestmap'), 'effector_actions', ['detection_timestmap'], unique=False)
    op.create_index(op.f('ix_effector_actions_id'), 'effector_actions', ['id'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recording_timestamp', sa.DateTime(), nullable=True),
    sa.Column('recording_duration', sa.Integer(), nullable=True),
    sa.Column('recording_file_path', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordings_id'), 'recordings', ['id'], unique=False)
    op.create_index(op.f('ix_recordings_recording_duration'), 'recordings', ['recording_duration'], unique=False)
    op.create_index(op.f('ix_recordings_recording_file_path'), 'recordings', ['recording_file_path'], unique=False)
    op.create_index(op.f('ix_recordings_recording_timestamp'), 'recordings', ['recording_timestamp'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detected_class', sa.String(), nullable=True),
    sa.Column('detection_timestmap', sa.DateTime(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_confidence'), 'detections', ['confidence'], unique=False)
    op.create_index(op.f('ix_detections_detected_class'), 'detections', ['detected_class'], unique=False)
    op.create_index(op.f('ix_detections_detection_timestmap'), 'detections', ['detection_timestmap'], unique=False)
    op.create_index(op.f('ix_detections_id'), 'detections', ['id'], unique=False)
    op.create_index(op.f('ix_detections_model_version'), 'detections', ['model_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detections_model_version'), table_name='detections')
    op.drop_index(op.f('ix_detections_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_detection_timestmap'), table_name='detections')
    op.drop_index(op.f('ix_detections_detected_class'), table_name='detections')
    op.drop_index(op.f('ix_detections_confidence'), table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_recordings_recording_timestamp'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_recording_file_path'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_recording_duration'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_id'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_effector_actions_id'), table_name='effector_actions')
    op.drop_index(op.f('ix_effector_actions_detection_timestmap'), table_name='effector_actions')
    op.drop_index(op.f('ix_effector_actions_action_timestamp'), table_name='effector_actions')
    op.drop_index(op.f('ix_effector_actions_action'), table_name='effector_actions')
    op.drop_table('effector_actions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
