"""SunriseTable

Revision ID: 8fe5ef3cc6b5
Revises: e91ce339a2d4
Create Date: 2025-01-25 13:51:10.846855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import csv
import datetime


# revision identifiers, used by Alembic.
revision: str = '8fe5ef3cc6b5'
down_revision: Union[str, None] = 'e91ce339a2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sunset_sunrise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('sunrise', sa.DateTime(), nullable=True),
    sa.Column('sunset', sa.DateTime(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sunset_sunrise_city'), 'sunset_sunrise', ['city'], unique=False)
    op.create_index(op.f('ix_sunset_sunrise_day'), 'sunset_sunrise', ['day'], unique=False)
    op.create_index(op.f('ix_sunset_sunrise_id'), 'sunset_sunrise', ['id'], unique=False)
    op.create_index(op.f('ix_sunset_sunrise_month'), 'sunset_sunrise', ['month'], unique=False)
    # ### end Alembic commands ###
    # add data to the table from sunrise_sunset.csv
    # write current wd to a file
    with open("alembic/versions/sunrise_sunset.csv") as f:
        reader = csv.reader(f)
        next(reader)
        for index,row in enumerate(reader):
            id = index
            month = row[0]
            day = row[1]
            sunrise = datetime.datetime.strptime(row[2].split('+')[0], "%Y-%m-%d %H:%M:%S")
            sunset = datetime.datetime.strptime(row[3].split('+')[0], "%Y-%m-%d %H:%M:%S")
            city = row[4]
            op.execute(
                f"INSERT INTO sunset_sunrise (id, month, day, sunrise, sunset, city) VALUES ({id}, {month}, {day}, '{sunrise}', '{sunset}', '{city}')"
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sunset_sunrise_month'), table_name='sunset_sunrise')
    op.drop_index(op.f('ix_sunset_sunrise_id'), table_name='sunset_sunrise')
    op.drop_index(op.f('ix_sunset_sunrise_day'), table_name='sunset_sunrise')
    op.drop_index(op.f('ix_sunset_sunrise_city'), table_name='sunset_sunrise')
    op.drop_table('sunset_sunrise')
    # ### end Alembic commands ###
