"""Added new tables

Revision ID: e91ce339a2d4
Revises: 
Create Date: 2024-06-29 09:29:02.633283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91ce339a2d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recording_timestamp', sa.DateTime(), nullable=True),
    sa.Column('recording_end_timestamp', sa.DateTime(), nullable=True),
    sa.Column('recording_file_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordings_id'), 'recordings', ['id'], unique=False)
    op.create_index(op.f('ix_recordings_recording_end_timestamp'), 'recordings', ['recording_end_timestamp'], unique=False)
    op.create_index(op.f('ix_recordings_recording_file_path'), 'recordings', ['recording_file_path'], unique=False)
    op.create_index(op.f('ix_recordings_recording_timestamp'), 'recordings', ['recording_timestamp'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detected_class', sa.String(), nullable=True),
    sa.Column('detection_timestamp', sa.DateTime(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_detected_class'), 'detections', ['detected_class'], unique=False)
    op.create_index(op.f('ix_detections_detection_timestamp'), 'detections', ['detection_timestamp'], unique=False)
    op.create_index(op.f('ix_detections_id'), 'detections', ['id'], unique=False)
    op.create_table('effector_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('action_metadata', sa.String(), nullable=True),
    sa.Column('detection_timestamp', sa.DateTime(), nullable=True),
    sa.Column('action_timestamp', sa.DateTime(), nullable=True),
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.Column('detection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_effector_actions_action'), 'effector_actions', ['action'], unique=False)
    op.create_index(op.f('ix_effector_actions_action_timestamp'), 'effector_actions', ['action_timestamp'], unique=False)
    op.create_index(op.f('ix_effector_actions_detection_timestamp'), 'effector_actions', ['detection_timestamp'], unique=False)
    op.create_index(op.f('ix_effector_actions_id'), 'effector_actions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_effector_actions_id'), table_name='effector_actions')
    op.drop_index(op.f('ix_effector_actions_detection_timestamp'), table_name='effector_actions')
    op.drop_index(op.f('ix_effector_actions_action_timestamp'), table_name='effector_actions')
    op.drop_index(op.f('ix_effector_actions_action'), table_name='effector_actions')
    op.drop_table('effector_actions')
    op.drop_index(op.f('ix_detections_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_detection_timestamp'), table_name='detections')
    op.drop_index(op.f('ix_detections_detected_class'), table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_recordings_recording_timestamp'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_recording_file_path'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_recording_end_timestamp'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_id'), table_name='recordings')
    op.drop_table('recordings')
    # ### end Alembic commands ###
